### ISSUE TITLE
Plugin not Found

### ISSUE THREAD

**Issue by MarvinPT** [Va1/browser-sync-webpack-plugin#22]
I've found this issue with a build 2 days ago, and never happen before.

`ReferenceError: Plugin is not defined
    at Object.<anonymous> ((...)/node_modules/browser-sync-webpack-plugin/index.js:21:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> ((...)/webpack.config.js:2:25)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)`

I'm using the following code in webpack.config.js

`plugins: [
    new BrowserSyncPlugin({
      host: 'localhost',
      port: 3000,
      proxy: 'localhost:4000'
    })
  ]`

Also my co worker mentioned the sync stop working altogether in his machine, but mine still works as normal. 

I don't know if this is related to this plugin specifically or with Webpack/Browser Sync in general.

p.s. found out that someone else had the same issue in Stackoverflow: 

http://stackoverflow.com/questions/37628622/webpack-and-browsersync-plugin-not-defined

**Comment by MarvinPT** [comment]
version 1.0.3 fixed this issue.
